spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanager
    username: taskmanager
    password: taskmanager
  jpa:
    hibernate:
      ddl-auto: validate

cloud:
  aws:
    region:
      static: us-east-1
    sqs:
      endpoint: http://localhost:4566
    credentials:
      access-key: test
      secret-key: test
